# Generated by Django 5.0.7 on 2024-07-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oralapp', '0002_alter_emp_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='address',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterModelTable(
            name='emp',
            table='employee',
        ),
    ]
