# Generated by Django 5.0.7 on 2024-07-24 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incomeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addincome',
            old_name='incomedate',
            new_name='income_date',
        ),
        migrations.RenameField(
            model_name='addincome',
            old_name='incometype',
            new_name='income_type',
        ),
    ]
