# Generated by Django 5.0.7 on 2024-07-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomeapp', '0002_rename_incomedate_addincome_income_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addincome',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
