# Generated by Django 5.0.7 on 2024-07-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='income',
            field=models.IntegerField(),
        ),
    ]
