# Generated by Django 5.0.7 on 2024-08-10 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houseapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='p_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='p_bhk',
            new_name='bhk',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='p_contact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='p_ownername',
            new_name='owner_name',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='p_price',
            new_name='price',
        ),
    ]
