# Generated by Django 5.0.7 on 2024-08-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseapp', '0002_rename_p_description_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='img',
            field=models.ImageField(default='', upload_to='image'),
        ),
    ]
