# Generated by Django 5.0.7 on 2024-08-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseapp', '0003_property_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='img',
            field=models.ImageField(default='', upload_to='video'),
        ),
    ]
