# Generated by Django 5.0.7 on 2024-08-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseapp', '0004_alter_property_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='img',
            field=models.FileField(default='', upload_to='videos/'),
        ),
    ]
