# Generated by Django 5.0.7 on 2024-08-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseapp', '0006_property_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.CharField(max_length=40),
        ),
    ]
