# Generated by Django 5.0.7 on 2024-08-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseapp', '0007_alter_property_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='contact',
            field=models.CharField(max_length=15),
        ),
    ]
